### PR TITLE
[test] All test within test folder  now pass

### PR DESCRIPTION
**Pull request by Maurice-Hayward**
Before ./node_modules/mocha/bin/mocha test/  would fail now all test pass
-Removed references to smokesignals.Trailpack
-made the test more inline with trailsjs/trailpack-swagger (adding an Api folder)
-Since express and waterline are required add express, trailpack-express,  trailpack-waterline, and trailpack-router. to App.js of the test
-also, added the waterline-sqlite3 adapter to app.js of test to allow waterline to work properly

### CODE REVIEW

**Comment by matteozambon89** [comment]
@Maurice-Hayward I'm happy to see somebody is helping out with this Trailpack!
I'll be able to merge your pull request as soon as Travis is not failing anymore. 👍

**Comment by matteo-harpoon** [comment]
@Maurice-Hayward awesome! Let me know when I can merge 👍

**Comment by matteozambon89** [comment]
@Maurice-Hayward awesome! Let me know when I can merge 👍

**Comment by Maurice-Hayward** [comment]
@matteozambon89 no problem! I'm not making any more changes right now, so you can merge at any time.

**Comment by Maurice-Hayward** [comment]
@matteozambon89 are there any problems merging the commits, If so I can change things on my end. I just realized I might have done too many things for just one pull request.

**Comment by matteozambon89** [comment]
@Maurice-Hayward to be honest I thought I merged it already! sorry! I'll do it right now.

**Comment by Maurice-Hayward** [comment]
awesome!

**Comment by matteozambon89** [comment]
@Maurice-Hayward I've published a new version on npm too.

**Pull request merged**
